{"timestamp":"2025-08-16T19:01:53.990853","level":"info","event":"DAG bundles loaded: dags-folder, example_dags","logger":"airflow.dag_processing.bundles.manager.DagBundlesManager"}
{"timestamp":"2025-08-16T19:01:53.991178","level":"info","event":"Filling up the DagBag from /opt/airflow/dags/grok_migration.py","logger":"airflow.models.dagbag.DagBag"}
{"timestamp":"2025-08-16T19:01:54.274162Z","level":"info","event":"Task instance is in running state","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-16T19:01:54.274290Z","level":"info","event":" Previous state of the Task instance: TaskInstanceState.QUEUED","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-16T19:01:54.274375Z","level":"info","event":"Current task name:create_raw_schema","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-16T19:01:54.274425Z","level":"info","event":"Dag name:GROK_migrate","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-16T19:01:54.277402","level":"warning","event":"/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py:471: DeprecationWarning: Using Connection.get_connection_from_secrets from `airflow.models` is deprecated.Please use `from airflow.sdk import Connection` instead\n  warnings.warn(\n","logger":"py.warnings"}
{"timestamp":"2025-08-16T19:01:54.284874","level":"info","event":"Connection Retrieved 'pg_raw'","logger":"airflow.hooks.base"}
{"timestamp":"2025-08-16T19:01:54.284990","level":"warning","event":"This setter is for backward compatibility and should not be used.\nSince the introduction of connection property, the providers listed below breaks due to assigning value to self.connection in their __init__ method.\n* apache-airflow-providers-mysql<5.7.1\n* apache-airflow-providers-elasticsearch<5.5.1\n* apache-airflow-providers-postgres<5.13.0","logger":"airflow.task.hooks.airflow.providers.postgres.hooks.postgres.PostgresHook"}
{"timestamp":"2025-08-16T19:01:54.288896","level":"info","event":"Connection Retrieved 'pg_raw'","logger":"airflow.hooks.base"}
{"timestamp":"2025-08-16T19:01:55.947594","level":"error","event":"Task failed with exception","logger":"task","error_detail":[{"exc_type":"OperationalError","exc_value":"(psycopg2.OperationalError) connection to server at \"db-thanhnv164-postgres.ceahrljdchqz.us-east-1.rds.amazonaws.com\" (3.227.45.54), port 5432 failed: FATAL:  database \"raw\" does not exist\n\n(Background on this error at: https://sqlalche.me/e/14/e3q8)","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":890,"name":"run"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":1177,"name":"_execute_task"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/bases/operator.py","lineno":397,"name":"wrapper"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":217,"name":"execute"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":240,"name":"execute_callable"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/callback_runner.py","lineno":81,"name":"run"},{"filename":"/opt/airflow/dags/grok_migration.py","lineno":56,"name":"create_schema"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py","lineno":3153,"name":"begin"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py","lineno":3325,"name":"connect"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py","lineno":96,"name":"__init__"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py","lineno":3404,"name":"raw_connection"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py","lineno":3374,"name":"_wrap_pool_connect"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py","lineno":2208,"name":"_handle_dbapi_exception_noconnection"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py","lineno":211,"name":"raise_"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py","lineno":3371,"name":"_wrap_pool_connect"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py","lineno":327,"name":"connect"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py","lineno":894,"name":"_checkout"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py","lineno":493,"name":"checkout"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py","lineno":145,"name":"_do_get"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py","lineno":70,"name":"__exit__"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py","lineno":211,"name":"raise_"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py","lineno":143,"name":"_do_get"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py","lineno":273,"name":"_create_connection"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py","lineno":388,"name":"__init__"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py","lineno":690,"name":"__connect"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py","lineno":70,"name":"__exit__"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py","lineno":211,"name":"raise_"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py","lineno":686,"name":"__connect"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/create.py","lineno":574,"name":"connect"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/default.py","lineno":598,"name":"connect"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py","lineno":122,"name":"connect"}],"is_group":false,"exceptions":[]},{"exc_type":"OperationalError","exc_value":"connection to server at \"db-thanhnv164-postgres.ceahrljdchqz.us-east-1.rds.amazonaws.com\" (3.227.45.54), port 5432 failed: FATAL:  database \"raw\" does not exist\n","exc_notes":[],"syntax_error":null,"is_cause":true,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py","lineno":3371,"name":"_wrap_pool_connect"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py","lineno":327,"name":"connect"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py","lineno":894,"name":"_checkout"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py","lineno":493,"name":"checkout"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py","lineno":145,"name":"_do_get"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py","lineno":70,"name":"__exit__"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py","lineno":211,"name":"raise_"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py","lineno":143,"name":"_do_get"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py","lineno":273,"name":"_create_connection"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py","lineno":388,"name":"__init__"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py","lineno":690,"name":"__connect"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py","lineno":70,"name":"__exit__"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py","lineno":211,"name":"raise_"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py","lineno":686,"name":"__connect"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/create.py","lineno":574,"name":"connect"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/default.py","lineno":598,"name":"connect"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py","lineno":122,"name":"connect"}],"is_group":false,"exceptions":[]}]}
{"timestamp":"2025-08-16T19:01:55.949120Z","level":"info","event":"Task instance in failure state","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-16T19:01:55.949351Z","level":"info","event":"Task start","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-16T19:01:55.949465Z","level":"info","event":"Task:<Task(PythonOperator): create_raw_schema>","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-16T19:01:55.949562Z","level":"info","event":"Failure caused by (psycopg2.OperationalError) connection to server at \"db-thanhnv164-postgres.ceahrljdchqz.us-east-1.rds.amazonaws.com\" (3.227.45.54), port 5432 failed: FATAL:  database \"raw\" does not exist","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-16T19:01:55.949663Z","level":"info","event":"","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-16T19:01:55.949721Z","level":"info","event":"(Background on this error at: https://sqlalche.me/e/14/e3q8)","chan":"stdout","logger":"task"}
