{"timestamp":"2025-08-16T18:47:00.826530","level":"info","event":"DAG bundles loaded: dags-folder, example_dags","logger":"airflow.dag_processing.bundles.manager.DagBundlesManager"}
{"timestamp":"2025-08-16T18:47:00.826906","level":"info","event":"Filling up the DagBag from /opt/airflow/dags/grok_migration.py","logger":"airflow.models.dagbag.DagBag"}
{"timestamp":"2025-08-16T18:47:00.851800Z","level":"info","event":"Task instance is in running state","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-16T18:47:00.851909Z","level":"info","event":" Previous state of the Task instance: TaskInstanceState.QUEUED","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-16T18:47:00.851992Z","level":"info","event":"Current task name:create_raw_schema","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-16T18:47:00.852039Z","level":"info","event":"Dag name:GROK_mysql_to_postgres_raw_zone","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-16T18:47:00.853988","level":"warning","event":"/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py:471: DeprecationWarning: Using Connection.get_connection_from_secrets from `airflow.models` is deprecated.Please use `from airflow.sdk import Connection` instead\n  warnings.warn(\n","logger":"py.warnings"}
{"timestamp":"2025-08-16T18:47:00.857780","level":"info","event":"Connection Retrieved 'mysql_default'","logger":"airflow.hooks.base"}
{"timestamp":"2025-08-16T18:47:00.857890","level":"warning","event":"This setter is for backward compatibility and should not be used.\nSince the introduction of connection property, the providers listed below breaks due to assigning value to self.connection in their __init__ method.\n* apache-airflow-providers-mysql<5.7.1\n* apache-airflow-providers-elasticsearch<5.5.1\n* apache-airflow-providers-postgres<5.13.0","logger":"airflow.task.hooks.airflow.providers.mysql.hooks.mysql.MySqlHook"}
{"timestamp":"2025-08-16T18:47:00.866234","level":"error","event":"Task failed with exception","logger":"task","error_detail":[{"exc_type":"OperationalError","exc_value":"(MySQLdb.OperationalError) (1044, \"Access denied for user 'admin'@'%' to database 'raw'\")\n[SQL: CREATE SCHEMA IF NOT EXISTS raw;]\n(Background on this error at: https://sqlalche.me/e/14/e3q8)","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":890,"name":"run"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":1177,"name":"_execute_task"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/bases/operator.py","lineno":397,"name":"wrapper"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":217,"name":"execute"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":240,"name":"execute_callable"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/callback_runner.py","lineno":81,"name":"run"},{"filename":"/opt/airflow/dags/grok_migration.py","lineno":55,"name":"create_schema"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py","lineno":1370,"name":"execute"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py","lineno":1674,"name":"_exec_driver_sql"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py","lineno":1953,"name":"_execute_context"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py","lineno":2134,"name":"_handle_dbapi_exception"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py","lineno":211,"name":"raise_"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py","lineno":1910,"name":"_execute_context"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/default.py","lineno":736,"name":"do_execute"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/MySQLdb/cursors.py","lineno":179,"name":"execute"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/MySQLdb/cursors.py","lineno":330,"name":"_query"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/MySQLdb/connections.py","lineno":280,"name":"query"}],"is_group":false,"exceptions":[]},{"exc_type":"OperationalError","exc_value":"(1044, \"Access denied for user 'admin'@'%' to database 'raw'\")","exc_notes":[],"syntax_error":null,"is_cause":true,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py","lineno":1910,"name":"_execute_context"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/default.py","lineno":736,"name":"do_execute"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/MySQLdb/cursors.py","lineno":179,"name":"execute"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/MySQLdb/cursors.py","lineno":330,"name":"_query"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/MySQLdb/connections.py","lineno":280,"name":"query"}],"is_group":false,"exceptions":[]}]}
{"timestamp":"2025-08-16T18:47:00.867076Z","level":"info","event":"Task instance in failure state","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-16T18:47:00.867185Z","level":"info","event":"Task start","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-16T18:47:00.867250Z","level":"info","event":"Task:<Task(PythonOperator): create_raw_schema>","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-16T18:47:00.867339Z","level":"info","event":"Failure caused by (MySQLdb.OperationalError) (1044, \"Access denied for user 'admin'@'%' to database 'raw'\")","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-16T18:47:00.867396Z","level":"info","event":"[SQL: CREATE SCHEMA IF NOT EXISTS raw;]","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-16T18:47:00.867436Z","level":"info","event":"(Background on this error at: https://sqlalche.me/e/14/e3q8)","chan":"stdout","logger":"task"}
