{"timestamp":"2025-08-16T15:47:11.926251","level":"info","event":"DAG bundles loaded: dags-folder, example_dags","logger":"airflow.dag_processing.bundles.manager.DagBundlesManager"}
{"timestamp":"2025-08-16T15:47:11.927347","level":"info","event":"Filling up the DagBag from /opt/airflow/dags/raw_zone_migration.py","logger":"airflow.models.dagbag.DagBag"}
{"timestamp":"2025-08-16T15:47:12.007803Z","level":"info","event":"Task instance is in running state","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-16T15:47:12.007958Z","level":"info","event":" Previous state of the Task instance: TaskInstanceState.QUEUED","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-16T15:47:12.015160Z","level":"info","event":"Current task name:load_table_via_tempfile","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-16T15:47:12.015338Z","level":"info","event":"Dag name:test_rawzone_import","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-16T15:47:12.016378","level":"warning","event":"/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py:471: DeprecationWarning: Using Connection.get_connection_from_secrets from `airflow.models` is deprecated.Please use `from airflow.sdk import Connection` instead\n  warnings.warn(\n","logger":"py.warnings"}
{"timestamp":"2025-08-16T15:47:12.026201","level":"info","event":"Connection Retrieved 'mysql_default'","logger":"airflow.hooks.base"}
{"timestamp":"2025-08-16T15:47:12.026395","level":"warning","event":"This setter is for backward compatibility and should not be used.\nSince the introduction of connection property, the providers listed below breaks due to assigning value to self.connection in their __init__ method.\n* apache-airflow-providers-mysql<5.7.1\n* apache-airflow-providers-elasticsearch<5.5.1\n* apache-airflow-providers-postgres<5.13.0","logger":"airflow.task.hooks.airflow.providers.mysql.hooks.mysql.MySqlHook"}
{"timestamp":"2025-08-16T15:47:12.033128","level":"error","event":"load_table_via_tempfile failed for table=returns","logger":"root","error_detail":[{"exc_type":"TypeError","exc_value":"Connection.cursor() got an unexpected keyword argument 'dictionary'","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/opt/airflow/dags/raw_zone_migration.py","lineno":134,"name":"load_table_via_tempfile"}],"is_group":false,"exceptions":[]}]}
{"timestamp":"2025-08-16T15:47:12.033460","level":"error","event":"Task failed with exception","logger":"task","error_detail":[{"exc_type":"TypeError","exc_value":"Connection.cursor() got an unexpected keyword argument 'dictionary'","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":890,"name":"run"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":1177,"name":"_execute_task"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/bases/operator.py","lineno":397,"name":"wrapper"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/bases/decorator.py","lineno":251,"name":"execute"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/bases/operator.py","lineno":397,"name":"wrapper"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":217,"name":"execute"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":240,"name":"execute_callable"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/callback_runner.py","lineno":81,"name":"run"},{"filename":"/opt/airflow/dags/raw_zone_migration.py","lineno":134,"name":"load_table_via_tempfile"}],"is_group":false,"exceptions":[]}]}
{"timestamp":"2025-08-16T15:47:12.034471Z","level":"info","event":"Task instance in failure state","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-16T15:47:12.037254Z","level":"info","event":"Task start","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-16T15:47:12.037481Z","level":"info","event":"Task:<Task(_PythonDecoratedOperator): load_table_via_tempfile>","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-16T15:47:12.038214Z","level":"info","event":"Failure caused by Connection.cursor() got an unexpected keyword argument 'dictionary'","chan":"stdout","logger":"task"}
